// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSORghNnBuSJoldbDWJVNZ_3xEhtFHX04',
    appId: '1:310993412935:web:e7caa890c3127e4684a262',
    messagingSenderId: '310993412935',
    projectId: 'lushlane-app',
    authDomain: 'lushlane-app.firebaseapp.com',
    storageBucket: 'lushlane-app.firebasestorage.app',
    measurementId: 'G-NGQKJZ1G9Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOZNtQTLNjGzOYzP6L-Tt04yB16QgE3YM',
    appId: '1:310993412935:android:2881b519ede2b80f84a262',
    messagingSenderId: '310993412935',
    projectId: 'lushlane-app',
    storageBucket: 'lushlane-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPNeoEH_VxhLzpLErCMtusWeBzPAQeI44',
    appId: '1:310993412935:ios:57cffda8a16d27e484a262',
    messagingSenderId: '310993412935',
    projectId: 'lushlane-app',
    storageBucket: 'lushlane-app.firebasestorage.app',
    iosBundleId: 'com.example.lushlaneApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPNeoEH_VxhLzpLErCMtusWeBzPAQeI44',
    appId: '1:310993412935:ios:57cffda8a16d27e484a262',
    messagingSenderId: '310993412935',
    projectId: 'lushlane-app',
    storageBucket: 'lushlane-app.firebasestorage.app',
    iosBundleId: 'com.example.lushlaneApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSORghNnBuSJoldbDWJVNZ_3xEhtFHX04',
    appId: '1:310993412935:web:3d6b9b5faf1cffb684a262',
    messagingSenderId: '310993412935',
    projectId: 'lushlane-app',
    authDomain: 'lushlane-app.firebaseapp.com',
    storageBucket: 'lushlane-app.firebasestorage.app',
    measurementId: 'G-11ETEY915N',
  );
}
